spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource: 
    url: jdbc:mysql://localhost:3306/quintrix
    username: root
    password: Blackocean12!
    driver-class-name: com.mysql.cj.jdbc.Driver
    
agentService:
    getUrl: https://gorest.co.in/public/v2/users
    
logging:
    level:
        org.springframework: ERROR
        com.quintrix: DEBUG
    pattern:
        console: " %-5level %logger{36} - %msg%n"
        file: "%d %p %c{1.} [%t] %m%n"
    file: app.log