spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource: 
    url: jdbc:mysql://localhost:3306/quintrix
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver